[build]
  publish = "dist"
  command = "npm install && npm run build"

# Disable automatic service worker generation to prevent Response constructor errors
[build.environment]
  DISABLE_SERVICE_WORKER = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Prevent service worker related files from being served
[[redirects]]
  from = "/*sw*.js"
  to = "/404"
  status = 404
  force = true

[[redirects]]
  from = "/*cnm*.js"
  to = "/404"
  status = 404
  force = true